version: "3.7"  # optional since v1.27.0
services:
  app:
    build: .
    networks:
      - my_network

  redis:
    container_name: my-redis-container
    image: redis
    volumes:
      - redis_data:/data
    networks:
      - my_network
    ports:
      - 9999:6379

volumes:
  redis_data: {}

networks:
  my_network: {}
